name: Clang-Tidy
on:
  workflow_run:
    workflows: [ Unit Tests, Pull Request Unit Tests ]
    types: [ completed ]

jobs:
  clang-tidy-v6m:
    name: Clang-Tidy ARMv6M
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4.1.6
       with:
        submodules: 'true'

     - name: Configure the Build
       uses: threeal/cmake-action@main
       with:
        c-compiler: gcc
        run-build: false
        build-dir: static_analysis
        source-dir: testing/clang-tidy
        options: |
          CMRX_TARGET_PLATFORM=ARMv6M
          CMRX_UNIT_TESTS=OFF

     - name: Run Static Analysis
       run: cmake --build static_analysis -- clang-tidy

  clang-tidy-v7m:
    name: Clang-Tidy ARMv7M
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4.1.6
       with:
        submodules: 'true'

     - name: Configure the Build
       uses: threeal/cmake-action@main
       with:
        c-compiler: gcc
        run-build: false
        build-dir: static_analysis
        source-dir: testing/clang-tidy
        options: |
          CMRX_TARGET_PLATFORM=ARMv7M
          CMRX_UNIT_TESTS=OFF

     - name: Run Static Analysis
       run: cmake --build static_analysis -- clang-tidy

  clang-tidy-v7mf:
    name: Clang-Tidy ARMv7M-F
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4.1.6
       with:
        submodules: 'true'

     - name: Configure the Build
       uses: threeal/cmake-action@main
       with:
        c-compiler: gcc
        run-build: false
        build-dir: static_analysis
        source-dir: testing/clang-tidy
        options: |
          CMRX_TARGET_PLATFORM=ARMv7MF
          CMRX_UNIT_TESTS=OFF

     - name: Run Static Analysis
       run: cmake --build static_analysis -- clang-tidy
