name: 'Build: rp2040'
on:
  push:
    branches: [ master ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
     - name: Prepare Cross-Toolchain Environment
       uses: carlosperate/arm-none-eabi-gcc-action@v1
       with:
         release: '12.2.Rel1'
     - name: Checkout Test Sources
       uses: actions/checkout@v4.1.6
       with:
         repository: ventZl/cmrx-integration-tests
         submodules: 'false'

     - name: Checkout Latest CMRX Kernel
       uses: actions/checkout@v4.1.6
       with:
         repository: ventZl/cmrx
         path: rp2040-pico-sdk/cmrx
         submodules: 'false'

     - name: Checkout Latest Raspberry Pi Pico SDK
       uses: actions/checkout@v4.1.6
       with:
         repository: raspberrypi/pico-sdk
         path: rp2040-pico-sdk/pico-sdk
         submodules: 'false'

     - name: Configure Integration Test Build
       uses: threeal/cmake-action@main
       with:
        run-build: false
        source-dir: stm32h7-cubemx
        build-dir: build
        args: -DCMRX_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=Debug -DPICO_SDK_PATH=${{github.workspace}}/pico-sdk

     - name: Pre-build Integration Test
       run: make -C build
       continue-on-error: true

     - name: Build Integration Test
       run: make -C build
